# Week 5 (starter): RAG Pipeline with Retrieval Evaluation

Retrieval runs fully local and free; only generation needs a key (set `GEMINI_API_KEY`, else it is skipped with a notice). Cells marked **TODO (you)** are yours. Dependencies: `sentence-transformers`, `faiss-cpu`. For generation: `pip install openai`.

In [1]:
import os, re, pathlib, numpy as np
os.environ['HF_HOME'] = str((pathlib.Path('.') / '.hf_cache').resolve())
from sentence_transformers import SentenceTransformer
import faiss
embedder = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

c:\Users\wyatt\Documents\Gradschool\cosc_650\repos\cosc-650-applied-llm-systems\src\week5\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2700.81it/s]

## Part 1: Build the pipeline
Ingest and chunk a documentation corpus of at least eight documents, embed the chunks locally with sentence-transformers, and store them in a vector index (FAISS or similar). Implement retrieval that embeds a query and returns the top-k chunks.

In [2]:
from pypdf import PdfReader

DOCS_DIR = pathlib.Path("gardening_docs")

def load_pdf(file_path):
    reader = PdfReader(file_path)
    pages = []

    for page in reader.pages:
        text = page.extract_text()

        if text:
            pages.append(text)

    return "\n\n".join(pages)


documents = []

for file_path in DOCS_DIR.glob("*.pdf"):
    documents.append({
        "source": file_path.name,
        "text": load_pdf(file_path)
    })


print(f"Loaded {len(documents)} documents")

for doc in documents:
    print(f"{doc['source']}: {len(doc['text']):,} characters")

Loaded 8 documents
bush_gardening.pdf: 147,544 characters
fruit_gardening.pdf: 24,727 characters
gardening_beds.pdf: 20,128 characters
gardening_pests.pdf: 10,832 characters
gardening_planters.pdf: 34,943 characters
grass_gardening.pdf: 33,280 characters
tree_planting.pdf: 23,515 characters
vegetable_gardening.pdf: 78,865 characters

In [3]:
def chunk_fixed(text, size, overlap):
    text = re.sub(r'\s+', ' ', text).strip(); out, i = [], 0
    while i < len(text):
        out.append(text[i:i+size]); i += size - overlap
    return out

def chunk_paragraph(text):
    return [re.sub(r'\s+',' ',p).strip() for p in text.split('\n\n') if p.strip()]


def chunk_documents(documents, chunker):
    chunks = []

    for doc in documents:
        doc_chunks = chunker(doc["text"])

        for chunk_id, chunk in enumerate(doc_chunks):
            chunks.append({
                "source": doc["source"],
                "chunk_id": chunk_id,
                "text": chunk
            })

    return chunks


configs = {
    "small (120/20)": chunk_documents(
        documents,
        lambda text: chunk_fixed(text, 120, 20)
    ),
    "large (320/40)": chunk_documents(
        documents,
        lambda text: chunk_fixed(text, 320, 40)
    ),
    "by-paragraph": chunk_documents(
        documents,
        chunk_paragraph
    )
}

for n, c in configs.items():
    print(f'{n:16s} -> {len(c)} chunks')

def build(chunks):
    texts = [chunk["text"] for chunk in chunks]

    e = embedder.encode(
        texts,
        normalize_embeddings=True
    ).astype("float32")

    idx = faiss.IndexFlatIP(e.shape[1])
    idx.add(e)

    return idx

# def retrieve(idx, chunks, q, k=3):
#     qe = embedder.encode([q], normalize_embeddings=True).astype('float32')
#     # FAISS uses -1 for missing results when fewer than k chunks exist.
#     return [chunks[i] for i in idx.search(qe, k)[1][0] if i >= 0]

def retrieve(idx, chunks, q, k=3):
    qe = embedder.encode(
        [q],
        normalize_embeddings=True
    ).astype("float32")

    scores, indices = idx.search(qe, k)

    results = []

    for score, i in zip(scores[0], indices[0]):
        if i >= 0:
            results.append({
                "source": chunks[i]["source"],
                "chunk_id": chunks[i]["chunk_id"],
                "text": chunks[i]["text"],
                "score": float(score)
            })

    return results

small (120/20)   -> 3668 chunks
large (320/40)   -> 1313 chunks
by-paragraph     -> 200 chunks

In [4]:
indices = {
    name: build(chunks)
    for name, chunks in configs.items()
}

for name, idx in indices.items():
    print(f"{name:16s} -> {idx.ntotal} vectors")

small (120/20)   -> 3668 vectors
large (320/40)   -> 1313 vectors
by-paragraph     -> 200 vectors

In [5]:
query = "How much sunlight do vegetables need?"

results = retrieve(
    indices["by-paragraph"],
    configs["by-paragraph"],
    query,
    k=3
)

for i, result in enumerate(results, start=1):
    print(f"Result {i}")
    print(f"Source: {result['source']}")
    print(f"Chunk: {result['chunk_id']}")
    print(f"Score: {result['score']:.4f}")
    print(f"Text: {result['text']}")
    print()

Result 1
Source: vegetable_gardening.pdf
Chunk: 2
Score: 0.5475
Text: Vegetable Gardening 6-3 prune branches to allow in more light. If a solid fence is the source of the shade, consider replacing it with a post and rail fence that will let in more light. Light can be improved by painting nearby walls or fences white so they are more reflective. Areas receiving less sunlight may make a good composting site or work area. If the only garden site you have is shady, start by growing crops with low light requirements, such as leafy green crops like lettuce, or asparagus, garlic, and leeks. If these do well, expand into medium light-needing crops such as beans, radishes, and peas. Water. Regardless of where you live in Washington, if you are going to grow summer vegetables you will need a steady supply of clean water for irrigation all summer long. The easiest way to irrigate is from a water spigot located in or near your vegetable garden. If the spigot is in an inconvenient place, you may want to extend the line and put a spigot closer to the garden. In climates that freeze, bury the pipe deep enough (below the soil frost line ) to prevent it from bursting. Check with your local water company and county building department to learn how deep the soil frost line is in your area, and to determine if there are any required permits or procedures for extending a water line. See the Watering section to learn more about how and when to irrigate your vegetable garden to conserve water and optimize crop production. If your garden is very wet during the winter, it will require drainage if you plan to grow winter vegetable crops. Use raised beds and deep pathways to create a drier growing area for winter crops (see the section on Raised Beds). Wind Protection. Vegetables tend to be very easily damaged by winds. Not only can plants be blown over, but if there are particles of soil in the wind, these will abrade leaves and stems, thereby sand blasting them. If your site is exposed to wind, plant or build a windbreak so that it protects the garden but does not shade plants. See “Trees Against the Wind” listed in Further Reading for details on planting a wind break. Soil Tilth. A deep, loose garden soil that is high in organic matter is ideal, but few gardens start out this way. If you are lucky enough to have such good soil, maintain it by adding compost each year. If your soil is poor quality to begin with, or if you cannot dig more than a few inches deep, or if it is full of rocks, you can slowly improve the soil by adding organic matter several times a year. See the section on Soil Management for suggestions on building soil tilth. Access and Convenience. It is best to plant your garden in an area where you have easy access for maintenance. Vegetables usually require care several times a week so choose a location that is convenient. You will also need to move things in and out of the garden such as wheelbarrows of compost. If you will be adding compost by the pickup load, make sure the garden gate area is large enough for this.

Result 2
Source: vegetable_gardening.pdf
Chunk: 1
Score: 0.4957
Text: 6-2 Vegetable Gardening Introduction Sustainable gardening means growing plants in an environmentally friendly way. In the vegetable garden, this may include using cover crops to improve soil tilth and nutrition, rotating crops to prevent disease, and choosing an irrigation system that conserves water and reduces disease pressure. Also, making the right choices regarding types of crops and varieties to grow will enable you to produce a healthy crop while reducing the need for pesticides. Many of the practices that we will discuss in this chapter are the same practices that are used in organic gardening. Our goal is to grow a healthy, productive vegetable garden while minimizing outside inputs such as purchased fertilizer and pesticides. In addition, by recycling plant debris through composting you will be able to reduce the amount of waste that your garden produces. In this chapter we will discuss common cultural practices and techniques to use in your vegetable garden. Some topics such as soils, fertility, and composting are covered in detail in separate chapters in this manual. Getting Started Establishing a new vegetable garden that will be successful requires some advance assessment and planning similar to implementing any landscape design. There are decisions to be made about exactly where the garden will be for best sun access and wind protection, what that site needs in terms of soil enhancement, what sort of beds will be set up, what methods of irrigation will be used, what types and quantities of vegetables will be grown, and so on. Some of these issues are ongoing and can be addressed or modified throughout the growing season or between seasons. Others, such as where the garden sits, are not so flexible. Also keep in mind your own needs as a gardener: if the garden is not where and what you want it to be, you will be less inclined to give it the attention it needs to be sustainable and successful. Choosing a Vegetable Garden Site The first step to growing a healthy and productive vegetable garden is selecting a site that has these four important elements: 1) Full sunlight. 2) Easy access to water. 3) Protection from heavy winds. 4) Soil with good tilth. Sunlight. Most summer vegetable crops need at least eight hours of direct sunlight a day. If trees or shrubs are shading your garden,

Result 3
Source: vegetable_gardening.pdf
Chunk: 25
Score: 0.4897
Text: 6-26 Vegetable Gardening Table 9. Minimum, maximum, and optimum soil temperatures for vegetable seed germination (Source: Knott’s Handbook for Vegetable Growers). Vegetable Minimum (°F) Optimum Range (°F) Optimum (°F) Maximum (°F) Asparagus 50 60–85 75 95 Bean 60 60–85 80 95 Bean, Lima 60 65–85 85 85 Beet 40 50–85 85 95 Cabbage 40 45–95 85 100 Carrot 40 45–85 80 95 Cauliflower 40 45–85 80 100 Celery 40 60–70 70 85 Chard 40 50–85 85 95 Corn 50 60–95 95 105 Cucumber 60 60–95 95 105 Eggplant 60 75–90 85 95 Lettuce 35 40–80 75 85 Muskmelon 60 75–95 90 100 Okra 60 70–95 95 105 Onion 35 50–95 75 95 Parsley 40 50–85 75 90 Parsnip 35 50–70 65 85 Pea 40 40–75 75 85 Pepper 60 65–95 85 95 Pumpkin 60 70–90 90 100 Radish 40 45–90 85 95 Spinach 35 45–75 70 85 Squash 60 70–95 95 100 Tomato 50 60–85 85 95 Turnip 40 60–105 85 105 Watermelon 60 70–95 95 105 As a general rule, the planting depth for most seeds is equal to twice the size of the seed. The planting depth for most small- seeded crops is 1/8 to ½ inch, while large-seed crops are generally planted 1–2 inches deep. Refer back to Table 7 for recommended planting depths for many specific vegetable crops. Seed large crops in rows, and place 2 seeds per planting hole (thinning one if both emerge) to ensure that you attain the correct plant stand (number of plants in a given area). Small crops such as radish can be sown close together in rows or broadcast seeded. Growing Transplants. Using transplants enables you to get a jump on the season and perhaps try some varieties and crops that might

## Part 2: Evaluate retrieval
Compare at least two embedding models, or at least three chunking configurations, on at least ten test queries for which you decide in advance which retrieved chunks count as relevant. Report precision and recall at the chunk level, and explain where the choices disagree and why.

In [7]:
def find_chunks(config_name, source, keywords):
    chunks = configs[config_name]

    print (f"config: {config_name} source: {source} keywords: {keywords}")
    # Allow either one keyword or a list of keywords
    if isinstance(keywords, str):
        keywords = [keywords]

    matches = []

    for chunk in chunks:
        if chunk["source"] != source:
            continue

        text_lower = chunk["text"].lower()

        if any(keyword.lower() in text_lower for keyword in keywords):
            matches.append(chunk)

    for chunk in matches:
        print(f"Chunk {chunk['chunk_id']}")
        print(chunk["text"])
        print("-" * 80)

    print(f"Found {len(matches)} matching chunks.")

The below function call was ran for every combination of query and chunking configuration. Then results were input into chatgpt 5.6 Sol to determine which chunks were relevant.

In [20]:
# Query 10: How should a lawn be watered and maintained?

# find_chunks(
#     "small (120/20)",
#     "grass_gardening.pdf",
#     "water"
# )

# find_chunks(
#     "large (320/40)",
#     "grass_gardening.pdf",
#     "water"
# )

# find_chunks(
#     "by-paragraph",
#     "grass_gardening.pdf",
#     "water"
# )
find_chunks(
    "by-paragraph",
    "grass_gardening.pdf",
    [
        "water",
        "watering",
        "irrigation",
        "maintenance",
        "mowing",
        "fertilizer",
        "fertilizing"
    ]
)

config: by-paragraph source: grass_gardening.pdf keywords: ['water', 'watering', 'irrigation', 'maintenance', 'mowing', 'fertilizer', 'fertilizing']
Chunk 0
DIRECTORY WATER SUPPLY � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 2 LOOKING AT LAWNS � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 3 BENEFITS OF LAWNS� � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 3 PLANTING A NEW LAWN � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 4 What Type of Grass to Plant � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 4 Perennial Ryegrass � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 4 Tall Fescues � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 5 Fine Fescues � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 5 Bentgrass � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 5 Kentucky Bluegrass � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 6 Waterwise Varieties � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 6 Ecolawns � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 6 When to Plant � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 6 Preparing the Soil � � � � � � � � � � � � � � � � � � � � � � � � � 7 Fertilizing � � � � � � � � � � � � � � � � � � � � � � � � � � � 8 Watering � � � � � � � � � � � � � � � � � � � � � � � � � � � � 9
--------------------------------------------------------------------------------
Chunk 1
CARING FOR YOUR ESTABLISHED LAWN � � � � � � � � � � � � � � � � 9 Watering � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 10 How Much to Water � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 11 Rain Sensor � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 12 Weekly Watering Number � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 12 Mowing � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 13 Fertilizing � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 14 Controlling Weeds � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 14 Controlling Moss � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 14 Aerating & Dethatching � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 15 Alternatives to Lawn � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 16 Groundcovers � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 16 Perennials and Shrubs � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 17 Hardscapes � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 17 RESOURCES � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 18 Water Audit � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 18 Websites and Books � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � � 19 1
--------------------------------------------------------------------------------
Chunk 2
WATER SUPPLY Here in the Portland metro area, water use can double or triple due to outdoor watering� This can be a problem because of the limited storage of our reservoirs and the typical lack of summer rainfall in the Pacific Northwest� By reducing summer water use, utilities can potentially delay building new storage facilities and transmission lines, and developing new sources of drinking water – all costly investments for communities� 2
--------------------------------------------------------------------------------
Chunk 3
Efficient use of water alone will not eliminate the need to increase our water supply, but it can make a big difference by postponing or reducing our need to build expensive new supply facilities� LOOKING AT LAWNS A lawn can be a serene oasis, an open expanse where kids can play and pets can roam, as well as a source of pride� But lawns can also use a lot of water� Lawns typically can use about 21/2 to 3 times as much water as many other plants in the landscape� Current research indicates that lawn watering typically results in as much as 30 percent water waste� This can be due to water lost through evaporation, runoff, overspray, and overwatering� The information in this booklet is designed to help you learn how to properly install and maintain your lawn with the appropriate amount of water and care� BENEFITS OF LAWN PROVIDES AESTHETICS - A well-maintained landscape can increase property value and create a sense of community pride� It complements trees and shrubs, and is ideal for foot traffic because it withstands trampling more than any other type of plant� PROVIDES RECREATION SURFACE - Grass provides an excellent recreation surface for outdoor activities � It is a low-cost safety cushion for sport participants and spectators, a healthy surface for picnics, yard games, and other outdoor activities, as well as a delight to walk on � It is also an ideal surface for dogs and other pets� REDUCES RUNOFF AND SOIL EROSION - Grass, due to its deep roots, can be effective in reducing runoff and preventing soil erosion � When it rains or when we water, pollutants are moved into the thatch and surface soil levels where they are trapped, preventing them from washing into our water systems� With up to 90 percent of the weight of a grass plant in its roots, it is no wonder that grass is a very efficient erosion prevention device� PROVIDES A COOLING EFFECT - Research shows that grass can be up to 30 degrees F cooler than concrete or blacktop and up to 14 degrees F cooler than bare soil� The cooling effect of an average lawn can equal over eight tons of air conditioning (the average home air conditioner produces four tons of cooled air)� The cooling effect is the result of the evaporation of water within the green leaves� Grass surfaces reduce temperature extremes by absorbing the sun’s heat during the day and by slowly releasing it in the evening, thus moderating excess temperatures� 3
--------------------------------------------------------------------------------
Chunk 4
ABSORBS DUST AND OTHER AIR POLLUTANTS - With its extensive and intertwined system of leaves and roots, grass surfaces around the world are estimated to trap some 12 million tons of dust and dirt from the air annually� CREATE A FUNCTIONAL LAWN AREA Whether installing a new landscape or redoing all or a portion of an existing landscape, it’s important to analyze your needs and expectations � Do you need a large recreational area for your family or pets? Do you want an area in the front of your home to appear green and well-manicured? Or, do you want to increase planting beds and reduce your lawn’s size? Are areas you are considering for new lawn easy to water and maintain? For example, is grass the best choice for narrow borders or parking strips? These are just a few of the important questions to ask yourself before making changes to your pre-existing lawn areas or planting a new lawn� PLANTING A NEW LAWN Selection of the type of grass to plant depends on your individual aesthetic and maintenance needs � Generally, in the Portland metro area, you want to plant a cool season grass since it is better adapted to our region’s climate� Warm season grasses are more successful in hot, dry climates � The following descriptions may help you decide which grass type best meets your needs� PERENNIAL RYEGRASS Perennial ryegrass is moderately dark green with good density and fine leaf texture� It is the most commonly planted grass in western Oregon, and is fairly drought tolerant� Lawn experts often recommend perennial ryegrass because it is easy to establish, grows vigorously, and can compete with weeds – therefore, deterring weed growth� This grass type is thatchless, allowing good water penetration� It’s disease-resistant with proper maintenance� In a mix with bluegrass and fine fescues it can be shade tolerant � It has a low growth habit, which is best mowed at 1 to 2 1/2 inches� 4
--------------------------------------------------------------------------------
Chunk 5
TALL FESCUES Tall fescue has a medium to dark green color and the deepest root system of grasses, with root system depths from 3 to 6 feet� It will stay greener longer in a drought if watered slowly and deeply� It is somewhat coarser in texture than perennial ryegrass � It also produces little thatch� Optimum mowing height for this grass type is 2 to 3 inches� FINE FESCUES Fine fescues are a deep green color and are often used in mixes with other grasses due to their ability to blend� It is often used in bluegrass mix - tures because it grows well in shade or dry soil � Fine fescues will go dormant in summer if water is withheld, but will “green up” quickly once moisture is applied again � Fine fescues do not develop thatch� This grass type does best with a mowing height of 1 to 2 1/2 inches or left unmown for the “meadow look�” BENTGRASS Bentgrass is usually an “invader grass” and it will take over even the best-maintained lawns planted with other seed types after a few years � It forms very dense, fine-textured patches, which hold the dew longer than other grasses � It dominates other lawn grasses because it grows well in the cool times of the year, tolerates drought by going dormant, requires very little fertilizer, and gets few diseases if it is not over-fertilized� If you don’t want it in your lawn, you’ll need quick removal by chemical means or hand weeding before patches enlarge� Creeping bentgrass is a specialty grass that requires high maintenance and expert management � It is typically used on golf courses due to its ability to withstand an extremely low cut (prefers mowing heights of 1 to 1 1/2 inches) as well as its ability to recover quickly from high traffic and other injuries, e� g�, divots� 5
--------------------------------------------------------------------------------
Chunk 6
KENTUCKY BLUEGRASS Kentucky Bluegrass is a cool season grass with a deep, rich dark green color and does best in cool, humid, and temperate climates � In the past, this type of grass was not widely used in the Pacific Northwest because it could not adapt well to our wet and mild winters� But, improvements have been made over the years to this grass type, which can make it a good choice for lawns in this area � It is moderately drought tolerant, but does not do well in partial or full shade� It can develop some thatch at higher nitrogen levels � Optimum mowing height is 1 1/2 to 2 inches� WATERWISE VARIETIE S New grass varieties are being developed that, once established, require less upkeep and watering than standard varieties � The Turf Grass Water Conservation Alliance (http://www �tgwca� org) is an independent foundation that tests and certifies grass mixture varieties that can survive under reduced or limited water� You can also ask your lawn and garden specialist for recommendations� ECOLAWNS An “ecolawn” is an alternative to conventional grass lawns� Ecolawns combine grasses with selected broadleaf plants such as herbs or flowers to produce an ecologically stable mixture of plants that require less maintenance than a typical lawn � Often these mixes take at least two seasons to become established� Check with your local nursery or lawn care professional for a mix you would enjoy� WHEN TO PLANT A NEW LAWN The best time to plant a new lawn in the Portland metro area is in the spring or fall so as to take advantage of rainfall and avoid the heat stress of summer � You can choose to either plant seed or install sod � Seeding may not be as effective after mid-October because of cooler temperatures and shorter days, but sod can be laid as late as November if the weather isn’t too severe� 6
--------------------------------------------------------------------------------
Chunk 7
PREPARING THE SOIL FOR A NEW LAWN The key to healthy grass is a deep root system - usually 8 to 24 inches deep� Healthy plant roots can penetrate several inches of topsoil for moisture, and can often go a week or more without water� In contrast, shallow root systems require more frequent watering as their root systems cannot reach the moisture that lies deeper in the soil� Before putting in new grass or sod it is very important to properly prepare your soil as this will save time and money in lawn maintenance once your lawn is established� For maximum growth and aesthetics, grass needs four essential factors: sunlight, air, water, and nutrients� Three of these four essential factors (air, water, and nutrients) are obtained from soil, but many soils lack the ability to provide these factors � The best soil conditions for lawn are loams, sandy loams, and clay loams (easily crumbled soils) with a pH of 6�0 to7�0� Almost all soils can be improved, but you need to know what your soil is comprised of before you can make the improvements� You can test your soil by taking soil core samples from several locations in your yard and have them analyzed by your local County Extension Office or a commercial soil-testing laboratory � Once you know your soil needs, you can then add the recommended amendments to increase its overall health� If your existing soil is healthy, till it 6 to 8 inches to loosen soil and break up large clods so it can be easily graded � Don’t pulverize it, however, as that can destroy the soil structure, reducing infiltration, and increasing compaction potential� If additional topsoil is needed, till your existing soil to a depth of at least 2 inches, then add 6-12 inches of good topsoil � Be sure that the soil textures and contents are the same (e� g� don’t add sandy soils to clay soils)� This will encourage the topsoil to bond to the subsoil, and improve root and water penetration� 7
--------------------------------------------------------------------------------
Chunk 8
Smooth, roll, and lightly rake the surface� Water the soil area thoroughly, up to 6 inches deep for best results � Then seed following the rates recommended on the seed package� Divide the grass seed in half and spread over the area twice in perpendicular directions to get consistent coverage� Rake the seed into the soil and roll again to firm and level the seedbed� If installing sod, roll it out after the soil is prepared as described above� FERTILIZING REQUIREMENTS FOR A NEW LAWN Fertilize new lawns with a 3-1-2 ratio of nitrogen (N), phosphorous (P), and potassium (K) at the time of installation, if seeded� If sod has not been pre-fertilized, then also fertilize when laying it� Nitrogen is the most important element for successful grass growth� Use 1 lb� of nitrogen per 1,000 sq� ft� at the time of seeding, and again 4 to 6 weeks later � These are the two most important fertilizer applications you will make to your grass� Each grass type, however, has its own requirements for fertilizing � Check with your local lawn care professional or consult the websites provided in the back of this brochure for more specific information� MULCHING NEW LAWNS Applying mulch to new seed plantings can provide the following benefits: a) keep moisture near the seeds during germination, b) help speed up germination, c) improve stand uniformity, and d) help to prevent soil erosion� Mulch should be applied lightly – between 1/8 and ¼ inches deep� Avoid using mulch when temperatures will be high as this can result in overheating of new seeds which can cause disease and/or heat scorch � Finer mulches work better than coarser ones (e�g� fresh sawdust, aged sawdust, compost)� 8
--------------------------------------------------------------------------------
Chunk 9
WATER REQUIREMENTS FOR NEW LAWNS New plantings need to be watered lightly and more frequently than established grass� In dry weather, new plantings should be watered 2-4 times a day until they germinate – usually 5 to 10 days if adequate moisture and optimal temperature� Water for as long as it takes for the soil surface to “glisten” - the length of time will depend on your soil’s texture� Once seeds have germinated, reduce your watering to 2 times per day until the end of the second week when you can reduce watering to 1 time a day� Continue to reduce your watering schedule so that by the third week you are watering every 2nd or 3rd day and by the fourth week 1-2 times per week� After that, water according to the lawn’s needs� If laying sod, follow within a half hour with at least 1 inch of water� You may need to do this in short time increments to avoid runoff� Water sod daily for the first few weeks � New sod and seed need to stay moist for the first few weeks to allow for successful establishment� For best results, follow the directions of your lawn care specialist until your new lawn is well established� CARING FOR AN ESTABLISHED LAWN Established lawns still need some tender loving care� If you practice appropriate maintenance, you will be pleased with the results and your lawn will be green and healthy� WATER REQUIREMENTS FOR ESTABLISHED LAWNS The greatest waste of water is watering too much, too often. The type of sprinkler system you select, the time and frequency you dedicate to watering, and the attention paid to your soil and lawn’s needs will help you water more efficiently and will result in a healthier lawn� Overwatering your lawn can lead to a variety of problems including shallow-rooted lawns, increased leaching of fertilizers and nutrients, and an increased potential for disease problems� Supplying too much water also causes grass to grow faster, which means more maintenance for you! 9
--------------------------------------------------------------------------------
Chunk 10

In [13]:
relevant_chunks = {
    "How much sunlight do vegetables need?": {
        "small (120/20)": {("vegetable_gardening.pdf", 28)},
        "large (320/40)": {("vegetable_gardening.pdf", 10)},
        "by-paragraph": {("vegetable_gardening.pdf", 1)}
    },

    "How should I choose a location for a vegetable garden?": {
        "small (120/20)": {("vegetable_gardening.pdf", 26),("vegetable_gardening.pdf", 27)},
        "large (320/40)": {("vegetable_gardening.pdf", 9)},
        "by-paragraph": {("vegetable_gardening.pdf", 1)}
    },

    "What type of soil is best for planting fruit trees?": {
        "small (120/20)": {("fruit_gardening.pdf", 12),("fruit_gardening.pdf", 13)},
        "large (320/40)": {("fruit_gardening.pdf", 4)},
        "by-paragraph": {("fruit_gardening.pdf", 0)}
    },

    "How should fruit trees be watered after planting?": {
        "small (120/20)": {("fruit_gardening.pdf", 39),("fruit_gardening.pdf", 46),("fruit_gardening.pdf", 47)},
        "large (320/40)": {("fruit_gardening.pdf", 14),("fruit_gardening.pdf", 16)},
        "by-paragraph": {("fruit_gardening.pdf", 0),("fruit_gardening.pdf", 1)}
    },

    "What are the benefits of using raised garden beds?": {
        "small (120/20)": {("gardening_beds.pdf", 26),
                            ("gardening_beds.pdf", 27),
                            ("gardening_beds.pdf", 28),
                            ("gardening_beds.pdf", 29),
                            ("gardening_beds.pdf", 30),
                            ("gardening_beds.pdf", 31),
                            ("gardening_beds.pdf", 32)},
        "large (320/40)": {("gardening_beds.pdf", 9),
                            ("gardening_beds.pdf", 10),
                            ("gardening_beds.pdf", 11),
                            ("gardening_beds.pdf", 13)},
        "by-paragraph": {("gardening_beds.pdf", 1)}
    },

    "How wide should a raised garden bed be?": {
        "small (120/20)": {("gardening_beds.pdf", 39)},
        "large (320/40)": {("gardening_beds.pdf", 14)},
        "by-paragraph": {("gardening_beds.pdf", 1)}
    },

    "How can crop rotation help control garden insects?": {
        "small (120/20)": {("gardening_pests.pdf", 22),
                            ("gardening_pests.pdf", 23),
                            ("gardening_pests.pdf", 24),
                            ("gardening_pests.pdf", 80)},
        "large (320/40)": {("gardening_pests.pdf", 7),("gardening_pests.pdf", 28)},
        "by-paragraph": {("gardening_pests.pdf", 0),("gardening_pests.pdf", 2)}
    },

    "How should shrubs be selected for different sunlight conditions?": {
        "small (120/20)": {("bush_gardening.pdf", 420),
                            ("bush_gardening.pdf", 421),
                            ("bush_gardening.pdf", 422),
                            ("bush_gardening.pdf", 568),
                            ("bush_gardening.pdf", 569),
                            ("bush_gardening.pdf", 570)},
        "large (320/40)": {("bush_gardening.pdf", 150),("bush_gardening.pdf", 203)},
        "by-paragraph": {("bush_gardening.pdf", 20),("bush_gardening.pdf", 27)}
    },

    "What should I consider when selecting a tree planting site?": {
        "small (120/20)": {("tree_planting.pdf", 15),
                            ("tree_planting.pdf", 16),
                            ("tree_planting.pdf", 17),
                            ("tree_planting.pdf", 18),
                            ("tree_planting.pdf", 19),
                            ("tree_planting.pdf", 20),
                            ("tree_planting.pdf", 21),
                            ("tree_planting.pdf", 27),
                            ("tree_planting.pdf", 28),
                            ("tree_planting.pdf", 29),
                            ("tree_planting.pdf", 30),
                            ("tree_planting.pdf", 31),
                            ("tree_planting.pdf", 32),
                            ("tree_planting.pdf", 33),
                            ("tree_planting.pdf", 34),
                            ("tree_planting.pdf", 35),
                            ("tree_planting.pdf", 36),
                            ("tree_planting.pdf", 37),
                            ("tree_planting.pdf", 38)},
        "large (320/40)": {("tree_planting.pdf", 5),
                            ("tree_planting.pdf", 6),
                            ("tree_planting.pdf", 10),
                            ("tree_planting.pdf", 12),
                            ("tree_planting.pdf", 13)},
        "by-paragraph": {("tree_planting.pdf", 1),("tree_planting.pdf", 2)}
    },

    "How should a lawn be watered and maintained?": {
        "small (120/20)": {("grass_gardening.pdf", 163),
                            ("grass_gardening.pdf", 164),
                            ("grass_gardening.pdf", 165),
                            ("grass_gardening.pdf", 166),
                            ("grass_gardening.pdf", 168),
                            ("grass_gardening.pdf", 169),
                            ("grass_gardening.pdf", 170),
                            ("grass_gardening.pdf", 171),
                            ("grass_gardening.pdf", 173),
                            ("grass_gardening.pdf", 174),
                            ("grass_gardening.pdf", 176),
                            ("grass_gardening.pdf", 177),
                            ("grass_gardening.pdf", 178),
                            ("grass_gardening.pdf", 179),
                            ("grass_gardening.pdf", 180),
                            ("grass_gardening.pdf", 181),
                            ("grass_gardening.pdf", 182),
                            ("grass_gardening.pdf", 183),
                            ("grass_gardening.pdf", 184),
                            ("grass_gardening.pdf", 185),
                            ("grass_gardening.pdf", 187),
                            ("grass_gardening.pdf", 189),
                            ("grass_gardening.pdf", 190),
                            ("grass_gardening.pdf", 191),
                            ("grass_gardening.pdf", 192),
                            ("grass_gardening.pdf", 200),
                            ("grass_gardening.pdf", 201),
                            ("grass_gardening.pdf", 204),
                            ("grass_gardening.pdf", 205),
                            ("grass_gardening.pdf", 206),
                            ("grass_gardening.pdf", 207),
                            ("grass_gardening.pdf", 208),
                            ("grass_gardening.pdf", 209),
                            ("grass_gardening.pdf", 210),
                            ("grass_gardening.pdf", 211),
                            ("grass_gardening.pdf", 216),
                            ("grass_gardening.pdf", 217),
                            ("grass_gardening.pdf", 218),
                            ("grass_gardening.pdf", 219),
                            ("grass_gardening.pdf", 220),
                            ("grass_gardening.pdf", 221),
                            ("grass_gardening.pdf", 230),
                            ("grass_gardening.pdf", 231),
                            ("grass_gardening.pdf", 232),
                            ("grass_gardening.pdf", 233),
                            ("grass_gardening.pdf", 237)},
        "large (320/40)": {("grass_gardening.pdf", 58),
                            ("grass_gardening.pdf", 59),
                            ("grass_gardening.pdf", 60),
                            ("grass_gardening.pdf", 61),
                            ("grass_gardening.pdf", 62),
                            ("grass_gardening.pdf", 63),
                            ("grass_gardening.pdf", 64),
                            ("grass_gardening.pdf", 65),
                            ("grass_gardening.pdf", 66),
                            ("grass_gardening.pdf", 67),
                            ("grass_gardening.pdf", 68),
                            ("grass_gardening.pdf", 71),
                            ("grass_gardening.pdf", 72),
                            ("grass_gardening.pdf", 73),
                            ("grass_gardening.pdf", 74),
                            ("grass_gardening.pdf", 77),
                            ("grass_gardening.pdf", 82),
                            ("grass_gardening.pdf", 83),
                            ("grass_gardening.pdf", 84)},
        "by-paragraph": {("grass_gardening.pdf", 9),
                        ("grass_gardening.pdf", 10),
                        ("grass_gardening.pdf", 11),
                        ("grass_gardening.pdf", 12),
                        ("grass_gardening.pdf", 13),
                        ("grass_gardening.pdf", 14),
                        ("grass_gardening.pdf", 15)}
    }
}

In [14]:
# TODO (you): your own queries and the fact each answer must contain.
test_queries = [
    "How much sunlight do vegetables need?",
    "How should I choose a location for a vegetable garden?",
    "What type of soil is best for planting fruit trees?",
    "How should fruit trees be watered after planting?",
    "What are the benefits of using raised garden beds?",
    "How wide should a raised garden bed be?",
    "How can crop rotation help control garden insects?",
    "How should shrubs be selected for different sunlight conditions?",
    "What should I consider when selecting a tree planting site?",
    "How should a lawn be watered and maintained?"
]
# This example checks whether retrieved context contains the answer.
# It does not calculate the chunk-level precision and recall required below.
# for n, c in configs.items():
#     hits = sum(1 for q, fact in qa if fact.lower() in ' '.join(retrieve(indices[n], c, q)).lower())
#     print(f'{n:16s} answer-recall@3: {hits}/{len(qa)} = {hits/len(qa):.2f}')
# TODO (you): compare at least two embedding models OR at least three chunking
# configurations on at least ten queries. Label relevant chunks in advance,
# report chunk-level precision and recall, and explain where the choices disagree.

In [15]:
def evaluate_query(config_name, query, k=3):
    chunks = configs[config_name]
    idx = indices[config_name]

    results = retrieve(idx, chunks, query, k=k)

    retrieved = {
        (result["source"], result["chunk_id"])
        for result in results
    }

    relevant = relevant_chunks[query][config_name]

    true_positives = retrieved & relevant
    
    precision = len(true_positives) / len(retrieved) if retrieved else 0.0
    recall = len(true_positives) / len(relevant) if relevant else 0.0

    return {
        "precision": precision,
        "recall": recall,
        "retrieved": retrieved,
        "relevant": relevant,
        "true_positives": true_positives
    }

In [16]:
import pandas as pd

evaluation_results = []

for query in test_queries:
    for config_name in configs:
        result = evaluate_query(
            config_name,
            query,
            k=3
        )

        evaluation_results.append({
            "query": query,
            "config": config_name,
            "precision@3": result["precision"],
            "recall@3": result["recall"],
            "hit@3": int(len(result["true_positives"]) > 0),
            "relevant_chunks": len(result["relevant"]),
            "true_positives": len(result["true_positives"])
        })

results_df = pd.DataFrame(evaluation_results)

results_df

,query,config,precision@3,recall@3,hit@3,relevant_chunks,true_positives
0,How much sunlight do vegetables need?,small (120/20),0.333333,1.000000,1,1,1
1,How much sunlight do vegetables need?,large (320/40),0.333333,1.000000,1,1,1
2,How much sunlight do vegetables need?,by-paragraph,0.333333,1.000000,1,1,1
3,How should I choose a location for a vegetable...,small (120/20),0.000000,0.000000,0,2,0
4,How should I choose a location for a vegetable...,large (320/40),0.333333,1.000000,1,1,1
5,How should I choose a location for a vegetable...,by-paragraph,0.333333,1.000000,1,1,1
6,What type of soil is best for planting fruit t...,small (120/20),0.333333,0.500000,1,2,1
7,What type of soil is best for planting fruit t...,large (320/40),0.000000,0.000000,0,1,0
8,What type of soil is best for planting fruit t...,by-paragraph,0.333333,1.000000,1,1,1
9,How should fruit trees be watered after planting?,small (120/20),0.000000,0.000000,0,3,0
10,How should fruit trees be watered after planting?,large (320/40),0.000000,0.000000,0,2,0
11,How should fruit trees be watered after planting?,by-paragraph,0.666667,1.000000,1,2,2
12,What are the benefits of using raised garden b...,small (120/20),0.000000,0.000000,0,7,0
13,What are the benefits of using raised garden b...,large (320/40),0.000000,0.000000,0,4,0
14,What are the benefits of using raised garden b...,by-paragraph,0.333333,1.000000,1,1,1
15,How wide should a raised garden bed be?,small (120/20),0.000000,0.000000,0,1,0
16,How wide should a raised garden bed be?,large (320/40),0.333333,1.000000,1,1,1
17,How wide should a raised garden bed be?,by-paragraph,0.000000,0.000000,0,1,0
18,How can crop rotation help control garden inse...,small (120/20),0.000000,0.000000,0,4,0
19,How can crop rotation help control garden inse...,large (320/40),0.000000,0.000000,0,2,0
20,How can crop rotation help control garden inse...,by-paragraph,0.333333,0.500000,1,2,1
21,How should shrubs be selected for different su...,small (120/20),0.333333,0.166667,1,6,1
22,How should shrubs be selected for different su...,large (320/40),0.666667,1.000000,1,2,2
23,How should shrubs be selected for different su...,by-paragraph,0.666667,1.000000,1,2,2
24,What should I consider when selecting a tree p...,small (120/20),0.000000,0.000000,0,19,0
25,What should I consider when selecting a tree p...,large (320/40),0.333333,0.200000,1,5,1
26,What should I consider when selecting a tree p...,by-paragraph,0.666667,1.000000,1,2,2
27,How should a lawn be watered and maintained?,small (120/20),0.000000,0.000000,0,46,0
28,How should a lawn be watered and maintained?,large (320/40),0.000000,0.000000,0,19,0
29,How should a lawn be watered and maintained?,by-paragraph,0.666667,0.285714,1,7,2

In [17]:
summary_df = (
    results_df
    .groupby("config")
    .agg({
        "precision@3": "mean",
        "recall@3": "mean",
        "hit@3": "mean"
    })
    .round(3)
)

summary_df

                precision@3  recall@3  hit@3
config
by-paragraph          0.433     0.779    0.9
large (320/40)        0.200     0.420    0.5
small (120/20)        0.100     0.167    0.3

The code below was used to verify top 3 chunks for queries. It requires some manual configuration for each query that needs a deeper dive.

In [13]:
query = "How should a lawn be watered and maintained?"
config_name = "small (120/20)"

result = evaluate_query(config_name, query, k=3)

retrieved_results = retrieve(
    indices[config_name],
    configs[config_name],
    query,
    k=3
)

for rank, chunk in enumerate(retrieved_results, start=1):
    chunk_key = (chunk["source"], chunk["chunk_id"])

    print(f"Rank {rank}")
    print(f"Source: {chunk['source']}")
    print(f"Chunk: {chunk['chunk_id']}")
    print(f"Score: {chunk['score']:.4f}")
    print(f"Relevant: {chunk_key in result['relevant']}")
    print(chunk["text"])
    print("-" * 80)

Rank 1
Source: grass_gardening.pdf
Chunk: 150
Score: 0.7824
Relevant: False
REQUIREMENTS FOR NEW LAWNS New plantings need to be watered lightly and more frequently than established grass� In dry w
--------------------------------------------------------------------------------
Rank 2
Source: grass_gardening.pdf
Chunk: 102
Score: 0.6911
Relevant: False
re being developed that, once established, require less upkeep and watering than standard varieties � The Turf Grass Wat
--------------------------------------------------------------------------------
Rank 3
Source: grass_gardening.pdf
Chunk: 298
Score: 0.6874
Relevant: False
 great lawn alternatives, offering much of a lawn’s neatness and uniformity but often with less water and maintenance re
--------------------------------------------------------------------------------

## Part 2 Analysis

### Retrieval Evaluation

The small (120/20), Large (320/40) and by-paragraph chunking strategies were tested using manually selected relevant chunks. The retriever returned the top 3 chunks and with this I was able to calculate the metrics below. Precision@3 measures how many of the top three retrieved chunks were actually relevant to the query, while Recall@3 measures how many of all the known relevant chunks were successfully found within those top three results. I added an additional metric hit@3 to show whether at least 1 relevant chunk was retrieved.

| Chunking Configuration | Precision@3 | Recall@3 | Hit@3 |
|------------------------|------------:|---------:|------:|
| Small (120/20)         | 0.100       | 0.167    | 0.300 |
| Large (320/40)         | 0.200       | 0.420    | 0.500 |
| By-paragraph           | 0.433       | 0.779    | 0.900 |


The table above shows the aggregated metrics for all three chunking strategies. We can see that by-paragraph performed the best for precision@3, recall@3 and hit@3. This strategy was able to retrieve at least 1 relevant chunk for 9 of the 10 test queries. 

### Differences Between Chunking Strategies

The results showed that the retrieval method performs poorly for the small chunk strategy. Looking at "How should a lawn be watered and maintained?" in particular, I observed 0s accross the board. Semantically similar chunks were often returned in the small strategy that did not included the desired context. Each matched word carries more weight when the chunks are smaller, and context is often left out of the chunk completely.

On the other hand, larger chunks contained more context. For the following test query "How should shrubs be selected for different sunlight conditions?", both large and paragraph strategies saw a recall@3 of 1.0 compared to .167 for small. We can also see a contradiction to this in the "How wide should a raised garden bed be?" test query, where the large strategy had a recall@3 of 1.0, while paragraph found no relevant chunks. This indicates that larger chunks do contain more context but can make detailed facts less prominent within the embeddings.

There is a clear limitation that recall suffers depending on the chunk size. For the following test query "What should I consider when selecting a tree planting site?" had 19 relevant small chunks, but only two relevant paragraphs. When you're using k=3, you will never retrieve all small chunks. So it's notable that recall does not only reflect performance but also the larger context of the chunks.

## Part 3: Generate
Add a generation step that builds a grounded prompt from the retrieved chunks and answers with the Gemini free tier.

In [18]:
def gemini_chat(messages, model='gemini-3.5-flash-lite', **kw):
    if not os.environ.get('GEMINI_API_KEY'):
        return None
    from openai import OpenAI
    client = OpenAI(api_key=os.environ['GEMINI_API_KEY'], base_url='https://generativelanguage.googleapis.com/v1beta/openai/')
    return client.chat.completions.create(model=model, messages=messages, **kw).choices[0].message.content

def answer(q, config='by-paragraph'):
    ctx = retrieve(indices[config], configs[config], q, k=3)
    prompt = 'Answer only from the context.\nContext:\n- ' + '\n- '.join(ctx) + f'\nQuestion: {q}\nAnswer:'
    out = gemini_chat([{'role':'user','content':prompt}])
    return out if out is not None else '[API-BLOCKED] set GEMINI_API_KEY to generate; grounded prompt was built'

def answer(q, config="by-paragraph"):
    ctx = retrieve(
        indices[config],
        configs[config],
        q,
        k=3
    )

    context = "\n\n".join(
        f"[Source: {chunk['source']}, Chunk: {chunk['chunk_id']}]\n"
        f"{chunk['text']}"
        for chunk in ctx
    )

    prompt = f"""Answer the question using only the provided context.
If the answer cannot be found in the context, say that the provided context does not contain enough information.

Context:
{context}

Question: {q}

Answer:"""

    out = gemini_chat([
        {
            "role": "user",
            "content": prompt
        }
    ])

    return (
        out if out is not None
        else "[API-BLOCKED] set GEMINI_API_KEY to generate; grounded prompt was built"
    )

In [15]:
import time
# generation_results = []

# for query in test_queries:
#     for config_name in configs:
#         time.sleep(10)
#         response = answer(
#             query,
#             config=config_name
#         )

#         generation_results.append({
#             "query": query,
#             "config": config_name,
#             "response": response
#         })

generation_df = pd.DataFrame(generation_results)

pd.set_option("display.max_colwidth", None)
generation_df

NameError: name 'generation_results' is not defined

## Part 4: Find one failure and explain it
Show a query where retrieval surfaces the wrong chunk, or where a chunking choice splits a fact away from the words that would find it. Explain the cause and the mitigation.

In [ ]:
query = "How should a lawn be watered and maintained?"
config = "small (120/20)"

results = retrieve(
    indices[config],
    configs[config],
    query,
    k=3
)

for rank, chunk in enumerate(results, start=1):
    print(f"Rank {rank}")
    print(f"Source: {chunk['source']}")
    print(f"Chunk: {chunk['chunk_id']}")
    print(f"Score: {chunk['score']:.4f}")
    print(f"Text: {chunk['text']}")
    print("-" * 80)

query = "How should a lawn be watered and maintained?"

response = answer(
    query,
    config="small (120/20)"
)

print(response)

Rank 1
Source: grass_gardening.pdf
Chunk: 150
Score: 0.7824
Text: REQUIREMENTS FOR NEW LAWNS New plantings need to be watered lightly and more frequently than established grass� In dry w
--------------------------------------------------------------------------------
Rank 2
Source: grass_gardening.pdf
Chunk: 102
Score: 0.6911
Text: re being developed that, once established, require less upkeep and watering than standard varieties � The Turf Grass Wat
--------------------------------------------------------------------------------
Rank 3
Source: grass_gardening.pdf
Chunk: 298
Score: 0.6874
Text:  great lawn alternatives, offering much of a lawn’s neatness and uniformity but often with less water and maintenance re
--------------------------------------------------------------------------------
Based on the provided context, new plantings need to be watered lightly and more frequently than established grass. Additionally, certain grass varieties and lawn alternatives are being developed that require less water and maintenance compared to standard varieties.

However, the provided context does not contain enough information to give a complete answer on how *all* lawns should generally be watered and maintained.

## Part 4 analysis

### Failure Analysis
For the following test query: "How should a lawn be watered and maintained?", the small chunking strategy failed to retrieve directly relevant chunks. The retrieved chunks discuss new lawns, low maintenance grass varieties and lawn alternatives. This resulted in Gimini providing a partial response and following our prompt to respond accordingly when context is insufficient.

As noted earlier, the small chunking strategy tends to leave out important context and prioritize semantic similarity. The retrieved chunks contained similar words such as lawn, water and maintenance, but did not contain context needed to answer the question.

We can mitigate this by using larger or paragraph chunk strategies to preserve context and improve retrieval. In this project, paragraph chunking was able to retrieve relevant information for this failure query. If you're intent on improve the small strategy performance, you could also increase overlap between small chunks to help retain realted information from being segmented.

## Week 6 Discussion

In [16]:
queries = [
    "What factors should I consider when choosing a location for my vegetable garden?",
    "How can I improve the soil in my garden before planting vegetables?",
    "How often should I water my vegetable garden, and what is the best way to water it?",
    "What are the benefits of using compost in a vegetable garden?",
    "How can I prevent and manage pests in my vegetable garden?"
]

config = "by-paragraph"

for i, query in enumerate(queries, start=1):
    print(f"\nQUERY {i}")
    print(f"Question: {query}")
    print("=" * 80)

    # Retrieve chunks
    results = retrieve(
        indices[config],
        configs[config],
        query,
        k=3
    )

    print("\nRETRIEVED CONTEXT")

    for rank, chunk in enumerate(results, start=1):
        print(f"\nRank {rank}")
        print(f"Source: {chunk['source']}")
        print(f"Chunk: {chunk['chunk_id']}")
        print(f"Score: {chunk['score']:.4f}")
        print(f"Text: {chunk['text']}")

    # Generate answer
    response = answer(
        query,
        config=config
    )

    print("\nGENERATED ANSWER")
    print(response)

    print("\n" + "-" * 80)

QUERY 1
Question: What factors should I consider when choosing a location for my vegetable garden?
================================================================================

RETRIEVED CONTEXT

Rank 1
Source: vegetable_gardening.pdf
Chunk: 1
Score: 0.6583
Text: 6-2 Vegetable Gardening Introduction Sustainable gardening means growing plants in an environmentally friendly way. In the vegetable garden, this may include using cover crops to improve soil tilth and nutrition, rotating crops to prevent disease, and choosing an irrigation system that conserves water and reduces disease pressure. Also, making the right choices regarding types of crops and varieties to grow will enable you to produce a healthy crop while reducing the need for pesticides. Many of the practices that we will discuss in this chapter are the same practices that are used in organic gardening. Our goal is to grow a healthy, productive vegetable garden while minimizing outside inputs such as purchased fertilizer and pesticides. In addition, by recycling plant debris through composting you will be able to reduce the amount of waste that your garden produces. In this chapter we will discuss common cultural practices and techniques to use in your vegetable garden. Some topics such as soils, fertility, and composting are covered in detail in separate chapters in this manual. Getting Started Establishing a new vegetable garden that will be successful requires some advance assessment and planning similar to implementing any landscape design. There are decisions to be made about exactly where the garden will be for best sun access and wind protection, what that site needs in terms of soil enhancement, what sort of beds will be set up, what methods of irrigation will be used, what types and quantities of vegetables will be grown, and so on. Some of these issues are ongoing and can be addressed or modified throughout the growing season or between seasons. Others, such as where the garden sits, are not so flexible. Also keep in mind your own needs as a gardener: if the garden is not where and what you want it to be, you will be less inclined to give it the attention it needs to be sustainable and successful. Choosing a Vegetable Garden Site The first step to growing a healthy and productive vegetable garden is selecting a site that has these four important elements: 1) Full sunlight. 2) Easy access to water. 3) Protection from heavy winds. 4) Soil with good tilth. Sunlight. Most summer vegetable crops need at least eight hours of direct sunlight a day. If trees or shrubs are shading your garden,

Rank 2
Source: vegetable_gardening.pdf
Chunk: 3
Score: 0.6201
Text: 6-4 Vegetable Gardening Site Protection. Another primary consideration for your vegetable garden is fencing. Deer can be a nuisance throughout the state and they may feed in your garden year-round. If you know there are deer in your area, be prepared to construct an 8-foot deer fence. Neighborhood dogs can also be destructive pests—digging, rolling and leaving droppings—so fencing them out as well is often necessary. See Chapter 18: Vertebrate Pest Management, for methods of dealing with other large pests. Design Once you have decided where your vegetable garden will be located, your next step is to design the garden layout. Committing your design to paper helps you plan quantities of seed, mulch, and other materials. It also serves as a record of what was done, to help with future design changes or rotational plantings. Many gardens often look like smaller versions of farms: long, single rows of vegetables with wide alleys between the rows. If you have lots of land and a rototiller, you may choose this system. If you have limited space or would like to maximize space usage, you may choose to use raised beds. See the Raised Beds section for information on how to make a raised bed. Pathways. Whether you choose to plant in rows or beds, make the main pathways in your garden at least 3 feet wide so that you can easily use a wheelbarrow. If you use a garden tractor, make sure you have room to drive in and out of the garden and to turn around if needed. If you plant vegetables in long, single rows, allow enough space to walk between the rows for weeding and harvesting. If your garden is arranged in raised beds, pathways between the beds should be wide enough for you to work. For example, if you work on your knees, measure the distance between the front of your knee and the toe of your shoe, then allow at least this much space for the width of your pathway. Do not make the beds or rows too wide: plan to plant, weed, water and harvest by reaching into the bed while standing or kneeling on the pathway to avoid compacting the soil within the bed. Cover all pathways with mulch or a cover crop to control weeds in the alleys and to keep your feet clean and dry year-round. For mulch, use wood chips, straw, pine needles, or any other product that is readily available in your area. To make the mulch more effective, first lay down heavy cardboard and then cover with mulch. If you use degradable mulch such as woodchips or straw, scrape the decomposed mulch off the pathways and into the rows or beds every 2 to 3 years and add new, fresh mulch to pathways. If you plant a cover crop in the alleyways, mow it several times a year to keep it from getting too tall and setting seed. If you use this technique, make sure your alleys are wide enough for your lawn mower. See the Cover Crop section for information about

Rank 3
Source: gardening_planters.pdf
Chunk: 17
Score: 0.5922
Text: Container Gardening The Anywhere Garden Concept! All you needs is sunshine, water, fertilizer, the right growing media, good plant choices and the desire to grow…. Container - Type, Size and Capacity Growing Media Choosing a Location Crop Selection for containers Care – Watering, Fertilization, and Growing Tips (Trellises and Supports) Suggested Vegetables for Container Growing

GENERATED ANSWER
Based on the provided context, the first step to growing a healthy and productive vegetable garden is selecting a site that has these four important elements:
1) Full sunlight (most summer vegetable crops need at least eight hours of direct sunlight a day)
2) Easy access to water
3) Protection from heavy winds
4) Soil with good tilth

Additionally, when establishing a new vegetable garden, you should consider best sun access and wind protection, what the site needs in terms of soil enhancement, what sort of beds will be set up, what methods of irrigation will be used, what types and quantities of vegetables will be grown, and your own needs as a gardener (so that you will be inclined to give it the attention it needs to be sustainable and successful).

--------------------------------------------------------------------------------

QUERY 2
Question: How can I improve the soil in my garden before planting vegetables?
================================================================================

RETRIEVED CONTEXT

Rank 1
Source: vegetable_gardening.pdf
Chunk: 7
Score: 0.6680
Text: 6-8 Vegetable Gardening Organic Matter. Plant residues such as fallen leaves, grass clippings, vegetable crop debris, and compost are all sources of organic matter for your vegetable garden. Naturally occurring bacteria and fungi in the soil decompose organic matter, turning it into humus, which is generally seen as the dark brown or black layer at the top of the soil. Soil organic matter generally accounts for only 1–5% of the total soil weight, whereas the majority of soil is made up of mineral particles in the form of sand, silt or clay. Soil organic matter improves soil tilth (soil health and structure), water-holding capacity, nutrient retention, nutrient availability, and aeration. Soil organic matter helps to improve soil structure by binding mineral soil particles together into larger soil aggregates. Large soil aggregates result in larger pore spaces that are available for air and water retention, and for root growth. Whether your soil is too heavy due to high clay content or too light due to high sand content, adding organic matter regularly is the best thing you can do to improve it. Soil that is high in organic matter is easier to work and generally is more productive than soil that lacks organic matter. To increase soil organic matter, add 2–3 inches of compost to the beds or rows each year. In addition, you can grow cover crops or use composted animal manures from local farms to build a healthy, productive soil. Building the soil. If your garden soil is very rocky or compacted, it is easiest to build the soil up over the course of several years rather than trying to dig deep the first year. To build your soil up, apply a 4–6 inch layer of compost uniformly over beds the first year. After you have applied the compost the first year, remove the top few inches of good soil from the paths and place it on top of the compost in the beds. This increases the depth of good soil in the beds and discourages weed growth in the poorer soil left in the paths. Apply a 2–3 inch layer of compost to the beds each year after. You can leave compost on the surface of the bed or you can turn it into the soil. Compost left on the surface will act as mulch and will help retain soil moisture and smother weeds. By incorporating the compost, you are placing nutrients where they are needed most—in the rooting zone. Whether you choose to leave the compost on top of the bed or turn it in, rake the beds to level them and to break up any large clods. Your decision may be based on how easy it is to turn the soil in your garden and you should do what is easiest for you. If your soil is compact and difficult to dig, plant deep-rooted vegetables such as tomatoes, winter squash, and melons for the first 2–3 years. Decomposing deep roots will create channels for water drainage and aeration, which will, in turn, enable medium- and shallow-rooted crops to grow and be more productive in following years. Compost. Compost is decomposed plant material and is easily made from plant residues from your garden and kitchen. Homemade compost is the easiest and least expensive way to provide your garden soil with fresh organic matter each year. In

Rank 2
Source: vegetable_gardening.pdf
Chunk: 32
Score: 0.6275
Text: Vegetable Gardening 6-33 Maintenance Plant Nutrition Plants require macro- and micronutrients to grow well and be productive. For fertilizer information and application methods, refer to Chapter 5: Plant Mineral Nutrition and Fertilizer. If you are adding compost to your garden each year, you may be adding sufficient levels of most macro- and micronutrients for adequate crop growth. To determine if your soil has appropriate nutrient levels to meet the needs of your vegetable crops, have your soil tested every 3 to 4 years. If your soil is low in one or more nutrients, add the appropriate fertilizer at the recommended rate to meet your crop needs. If the level of any nutrient in your soil is above the recommended level, reassess your practices so that you do not continue to add that nutrient. For example, compost made from dairy manure tends to be high in phosphorus (P) while compost made from poultry manure tends to be high in potassium (K). Remember that soil pH affects nutrient availability. In acid soils (at low soil pH), nutrients are not readily available for uptake by most vegetable crops. To increase nutrient availability, maintain a soil pH between 6.0 and 7.0. If you are adding compost to your garden each year, the organic matter will act slowly to increase soil pH. If your soil pH is still too low, add agricultural lime at the rate of about 6 pounds (12 cups) per 100 square feet for most soils. For clay soils, add 8 pounds of lime, and for sandy soils add 4 pounds. Lime does not react quickly in the soil and it takes at least half a year to be effective. In addition, water is needed to activate the lime; therefore it is best to apply lime in the fall. Lime is rarely needed in Eastern Washington. Watering Summers are quite dry throughout Washington, and you need to be prepared to water your vegetable garden from May through September. The amount of water and method of irrigation you use will often determine the success of your vegetable garden. The following is a guide to help you determine how best and how frequently to water. Timing. If you are using an overhead sprinkler, irrigate in the early mornings so that foliage can dry off before cool evening temperatures occur. Disease potential is increased when foliage remains wet during the night. If you use soaker hoses or drip irrigation, irrigate in the late afternoon or evening. By watering at the end of the day, more water will be absorbed into the soil and less water will be lost due to evaporation and transpiration, thereby increasing irrigation efficiency. Regardless of your irrigation method, do not irrigate in the heat of the day (11 am

Rank 3
Source: vegetable_gardening.pdf
Chunk: 6
Score: 0.6082
Text: Vegetable Gardening 6-7 when you cultivate for planting, when you incorporate compost, or when you till in plant residue after harvest. A rototiller will generally turn the top 5–6 inches of soil, while hand digging can reach a foot or more deep. Worm tunnels and decomposing deep plant roots will create channels several feet deep in the soil for aeration and water drainage. Soil that has high organic matter content will have large pore spaces that can be filled with air. A well-aerated, deep soil allows plants to establish a deep rooting system. Plants with deep root systems are more drought tolerant and more effective at capturing soil nutrients. It is especially important to have deep, well-aerated soils in intensive beds where plants are spaced close together and there is greater potential for competition for water and nutrients. Dig trench Pile soil Add compost Dig trench Pile soil Soil from first trench fills last trench Figure 1. Steps for double-digging a garden bed.

GENERATED ANSWER
Based on the provided context, you can improve your garden soil before planting vegetables in the following ways:

* **Add organic matter regularly:** Adding organic matter is the best thing you can do to improve soil that is either too heavy (high clay content) or too light (high sand content). You can increase soil organic matter by adding 2–3 inches of compost to the beds or rows each year, growing cover crops, or using composted animal manures from local farms.
* **Build up rocky or compacted soil over several years:**
  * Apply a 4–6 inch layer of compost uniformly over beds the first year.
  * Remove the top few inches of good soil from the paths and place it on top of the compost in the beds to increase the depth of good soil.
  * Apply a 2–3 inch layer of compost to the beds each year after. You can either leave the compost on the surface (to act as mulch, retain moisture, and smother weeds) or turn it into the soil (to place nutrients in the rooting zone).
  * Rake the beds to level them and break up large clods.
* **Plant deep-rooted vegetables:** If your soil is compact and difficult to dig, plant deep-rooted vegetables such as tomatoes, winter squash, and melons for the first 2–3 years. Their decomposing deep roots will create channels for water drainage and aeration, enabling medium- and shallow-rooted crops to grow better in following years.
* **Test and adjust nutrient levels and pH:** Have your soil tested every 3 to 4 years. Add appropriate fertilizers if the soil is low in nutrients. To increase nutrient availability and manage soil pH (maintaining it between 6.0 and 7.0), you can add compost or agricultural lime (at a recommended rate of about 6 pounds per 100 square feet for most soils, 8 pounds for clay soils, and 4 pounds for sandy soils, preferably applied in the fall).

--------------------------------------------------------------------------------

QUERY 3
Question: How often should I water my vegetable garden, and what is the best way to water it?
================================================================================

RETRIEVED CONTEXT

Rank 1
Source: vegetable_gardening.pdf
Chunk: 34
Score: 0.5836
Text: Vegetable Gardening 6-35 Calculating Amount to Irrigate. The amount of water that vegetable crops need is usually given in inches. For example, most vegetable crops require 1 inch of water (per square foot) every week. You can use indicators such as depth of soil moisture to determine if you have applied the right amount of water or you can measure and calculate the actual amount of water you apply. The easiest method for determining how long to irrigate is to simply use a shovel to check the depth of moisture in the soil, and adjust your watering schedule accordingly. For most clay and loam soils, 1 inch of water will penetrate about 6 inches deep. Measure the amount of time it takes for your first irrigation to wet the soil to a depth of 6 inches, and this is the amount of time it takes to apply 1 inch of water. Irrigate again for this same amount of time when the top 1–2 inches of soil is dry. After several weeks of irrigation, the soil should be moist throughout the root zone. At this point, you will only need to check the top 4–6 inches to see the soil moisture level. It is helpful to know that 1 inch of water per square foot equals 0.62 gallons. If you are watering by hand, apply 0.62 gallons per plant per week for those plants that are spaced more than a foot apart, or apply this same amount of water per linear foot of row for those crops that are spaced close together. To measure the amount of water you are applying with a sprinkler, place a bucket near one of the vegetable plants. Measure the depth of the water in the bucket after one hour; this will be the amount in inches that the plant received in that hour. Or, measure the volume of water in the bucket, and this will be the amount in gallons that the plant received. Use this measurement to determine how long to keep your sprinkler system on so that plants receive 1 inch of water. If you are using a sprinkler, measure the area (in square feet) of the garden that will be reached by the sprinkler. Multiply this number by the number of inches of water needed (1 inch in most cases), and then multiply by 0.62 (1 inch of water per square foot = 0.62 gal). This will give you the total number of gallons you need to apply. Divide the total number of gallons that you need to apply by the gallons-per-hour rate of your irrigation system to determine the irrigation time. Soaker hoses vary slightly in the amount of water they deliver, but in general they emit approximately 0.1 gallon per linear foot per hour. Soaker hoses generally wet an area of 6 inches on either side of the hose, or a 1-foot total width. You would need to irrigate six hours in order to apply the amount of water that is needed (0.62 gallon per square foot). You can measure the amount of water delivered by your soaker hose or drip tape by placing a container under the hose or tape. The volume of water in the container at the end of an hour tells you the number of gallons of water the plant is receiving. Or you can place the entire hose or 1 inch of water per square foot equals 0.62 gallons

Rank 2
Source: vegetable_gardening.pdf
Chunk: 33
Score: 0.5271

In [19]:
import sys
import langchain_community

print(sys.executable)
print(langchain_community.__version__)
import ragas

print(ragas.__version__)
from ragas.metrics import (
    Faithfulness,
    ResponseRelevancy,
    LLMContextPrecisionWithReference,
    LLMContextRecall,
)

c:\Users\wyatt\Documents\Gradschool\cosc_650\repos\cosc-650-applied-llm-systems\src\week5\.venv\Scripts\python.exe
0.3.31
0.3.9

In [20]:
import os

from langchain_openai import ChatOpenAI
from ragas.llms import LangchainLLMWrapper

gemini_evaluator = ChatOpenAI(
    model="gemini-3.5-flash-lite",
    api_key=os.environ["GEMINI_API_KEY"],
    base_url="https://generativelanguage.googleapis.com/v1beta/openai/",
    temperature=0,
)

evaluator_llm = LangchainLLMWrapper(gemini_evaluator)

C:\Users\wyatt\AppData\Local\Temp\ipykernel_18348\1294215970.py:13: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  evaluator_llm = LangchainLLMWrapper(gemini_evaluator)

In [21]:
test = gemini_evaluator.invoke("Reply with only: working")

print(test.content)

working

In [22]:
queries = [
    "What factors should I consider when choosing a location for my vegetable garden?",
    "How can I improve the soil in my garden before planting vegetables?",
    "How often should I water my vegetable garden, and what is the best way to water it?",
    "What are the benefits of using compost in a vegetable garden?",
    "How can I prevent and manage pests in my vegetable garden?"
]

references = [
    """
    Choose a vegetable garden site with full sunlight, easy access to water,
    protection from heavy winds, and soil with good tilth. Most summer
    vegetable crops need at least eight hours of direct sunlight per day.
    """,

    """
    Improve garden soil by regularly adding organic matter such as compost.
    Add 2–3 inches of compost to beds or rows each year. Cover crops and
    composted animal manure can also improve soil. For rocky or compacted
    soil, build the soil gradually and consider deep-rooted vegetables to
    improve drainage and aeration.
    """,

    """
    Seedlings and transplants should be watered every 2–3 days for the first
    week or two. Afterward, irrigate about once per week or as needed,
    providing approximately one inch of water per week. Soaker hoses and
    drip irrigation are more efficient than sprinklers because they reduce
    evaporation, runoff, weed growth, and problems associated with wet foliage.
    """,

    """
    Compost adds organic matter and nutrients to garden soil. Organic matter
    improves soil health and helps feed plants. Composting also allows garden
    debris and kitchen scraps to be recycled, reducing the amount of waste
    produced.
    """,

    """
    Prevent and manage garden pests by maintaining healthy plants, properly
    spacing plants, keeping the garden clean, identifying pests before
    treatment, scouting regularly, rotating crops, and using beneficial
    insects when appropriate. Removing weeds and old plant debris can also
    reduce places where pests live.
    """
]

In [23]:
evaluation_data = []

config = "by-paragraph"

for query, reference in zip(queries, references):

    results = retrieve(
        indices[config],
        configs[config],
        query,
        k=3
    )

    contexts = [
        chunk["text"]
        for chunk in results
    ]

    response = answer(
        query,
        config=config
    )

    evaluation_data.append({
        "user_input": query,
        "retrieved_contexts": contexts,
        "response": response,
        "reference": reference
    })

In [24]:
evaluation_data[0]

{'user_input': 'What factors should I consider when choosing a location for my vegetable garden?',
 'retrieved_contexts': ['6-2 Vegetable Gardening Introduction Sustainable gardening means growing plants in an environmentally friendly way. In the vegetable garden, this may include using cover crops to improve soil tilth and nutrition, rotating crops to prevent disease, and choosing an irrigation system that conserves water and reduces disease pressure. Also, making the right choices regarding types of crops and varieties to grow will enable you to produce a healthy crop while reducing the need for pesticides. Many of the practices that we will discuss in this chapter are the same practices that are used in organic gardening. Our goal is to grow a healthy, productive vegetable garden while minimizing outside inputs such as purchased fertilizer and pesticides. In addition, by recycling plant debris through composting you will be able to reduce the amount of waste that your garden produces. In this chapter we will discuss common cultural practices and techniques to use in your vegetable garden. Some topics such as soils, fertility, and composting are covered in detail in separate chapters in this manual. Getting Started Establishing a new vegetable garden that will be successful requires some advance assessment and planning similar to implementing any landscape design. There are decisions to be made about exactly where the garden will be for best sun access and wind protection, what that site needs in terms of soil enhancement, what sort of beds will be set up, what methods of irrigation will be used, what types and quantities of vegetables will be grown, and so on. Some of these issues are ongoing and can be addressed or modified throughout the growing season or between seasons. Others, such as where the garden sits, are not so flexible. Also keep in mind your own needs as a gardener: if the garden is not where and what you want it to be, you will be less inclined to give it the attention it needs to be sustainable and successful. Choosing a Vegetable Garden Site The first step to growing a healthy and productive vegetable garden is selecting a site that has these four important elements: 1) Full sunlight. 2) Easy access to water. 3) Protection from heavy winds. 4) Soil with good tilth. Sunlight. Most summer vegetable crops need at least eight hours of direct sunlight a day. If trees or shrubs are shading your garden,',
  '6-4 Vegetable Gardening Site Protection. Another primary consideration for your vegetable garden is fencing. Deer can be a nuisance throughout the state and they may feed in your garden year-round. If you know there are deer in your area, be prepared to construct an 8-foot deer fence. Neighborhood dogs can also be destructive pests—digging, rolling and leaving droppings—so fencing them out as well is often necessary. See Chapter 18: Vertebrate Pest Management, for methods of dealing with other large pests. Design Once you have decided where your vegetable garden will be located, your next step is to design the garden layout. Committing your design to paper helps you plan quantities of seed, mulch, and other materials. It also serves as a record of what was done, to help with future design changes or rotational plantings. Many gardens often look like smaller versions of farms: long, single rows of vegetables with wide alleys between the rows. If you have lots of land and a rototiller, you may choose this system. If you have limited space or would like to maximize space usage, you may choose to use raised beds. See the Raised Beds section for information on how to make a raised bed. Pathways. Whether you choose to plant in rows or beds, make the main pathways in your garden at least 3 feet wide so that you can easily use a wheelbarrow. If you use a garden tractor, make sure you have room to drive in and out of the garden and to turn around if needed. If you plant vegetables in long, single rows, allow enough space to walk between the rows for weeding and harvesting. If your garden is arranged in raised beds, pathways between the beds should be wide enough for you to work. For example, if you work on your knees, measure the distance between the front of your knee and the toe of your shoe, then allow at least this much space for the width of your pathway. Do not make the beds or rows too wide: plan to plant, weed, water and harvest by reaching into the bed while standing or kneeling on the pathway to avoid compacting the soil within the bed. Cover all pathways with mulch or a cover crop to control weeds in the alleys and to keep your feet clean and dry year-round. For mulch, use wood chips, straw, pine needles, or any other product that is readily available in your area. To make the mulch more effective, first lay down heavy cardboard and then cover with mulch. If you use degradable mulch such as woodchips or straw, scrape the decomposed mulch off the pathways and into the rows or beds every 2 to 3 years and add new, fresh mulch to pathways. If you plant a cover crop in the alleyways, mow it several times a year to keep it from getting too tall and setting seed. If you use this technique, make sure your alleys are wide enough for your lawn mower. See the Cover Crop section for information about',
  'Container Gardening The Anywhere Garden Concept! All you needs is sunshine, water, fertilizer, the right growing media, good plant choices and the desire to grow…. Container - Type, Size and Capacity Growing Media Choosing a Location Crop Selection for containers Care – Watering, Fertilization, and Growing Tips (Trellises and Supports) Suggested Vegetables for Container Growing'],
 'response': 'Based on the provided context, the first step to growing a healthy and productive vegetable garden is selecting a site that has these four important elements:\n\n1. Full sunlight (most summer vegetable crops need at least eight hours of direct sunlight a day).\n2. Easy access to water.\n3. Protection from heavy winds.\n4. Soil with good tilth.\n\nAdditionally, when choosing a location, you should consider decisions regarding best sun access and wind protection, what the site needs in terms of soil enhancement, and your own needs as a gardener so that it is where and what you want it to be.',
 'reference': '\n    Choose a vegetable garden site with full sunlight, easy access to water,\n    protection from heavy winds, and soil with good tilth. Most summer\n    vegetable crops need at least eight hours of direct sunlight per day.\n    '}

In [25]:
from ragas.dataset_schema import SingleTurnSample

samples = [
    SingleTurnSample(
        user_input=item["user_input"],
        response=item["response"],
        retrieved_contexts=item["retrieved_contexts"],
        reference=item["reference"],
    )
    for item in evaluation_data
]

In [26]:
print(samples[0])

user_input='What factors should I consider when choosing a location for my vegetable garden?' retrieved_contexts=['6-2 Vegetable Gardening Introduction Sustainable gardening means growing plants in an environmentally friendly way. In the vegetable garden, this may include using cover crops to improve soil tilth and nutrition, rotating crops to prevent disease, and choosing an irrigation system that conserves water and reduces disease pressure. Also, making the right choices regarding types of crops and varieties to grow will enable you to produce a healthy crop while reducing the need for pesticides. Many of the practices that we will discuss in this chapter are the same practices that are used in organic gardening. Our goal is to grow a healthy, productive vegetable garden while minimizing outside inputs such as purchased fertilizer and pesticides. In addition, by recycling plant debris through composting you will be able to reduce the amount of waste that your garden produces. In this chapter we will discuss common cultural practices and techniques to use in your vegetable garden. Some topics such as soils, fertility, and composting are covered in detail in separate chapters in this manual. Getting Started Establishing a new vegetable garden that will be successful requires some advance assessment and planning similar to implementing any landscape design. There are decisions to be made about exactly where the garden will be for best sun access and wind protection, what that site needs in terms of soil enhancement, what sort of beds will be set up, what methods of irrigation will be used, what types and quantities of vegetables will be grown, and so on. Some of these issues are ongoing and can be addressed or modified throughout the growing season or between seasons. Others, such as where the garden sits, are not so flexible. Also keep in mind your own needs as a gardener: if the garden is not where and what you want it to be, you will be less inclined to give it the attention it needs to be sustainable and successful. Choosing a Vegetable Garden Site The first step to growing a healthy and productive vegetable garden is selecting a site that has these four important elements: 1) Full sunlight. 2) Easy access to water. 3) Protection from heavy winds. 4) Soil with good tilth. Sunlight. Most summer vegetable crops need at least eight hours of direct sunlight a day. If trees or shrubs are shading your garden,', '6-4 Vegetable Gardening Site Protection. Another primary consideration for your vegetable garden is fencing. Deer can be a nuisance throughout the state and they may feed in your garden year-round. If you know there are deer in your area, be prepared to construct an 8-foot deer fence. Neighborhood dogs can also be destructive pests—digging, rolling and leaving droppings—so fencing them out as well is often necessary. See Chapter 18: Vertebrate Pest Management, for methods of dealing with other large pests. Design Once you have decided where your vegetable garden will be located, your next step is to design the garden layout. Committing your design to paper helps you plan quantities of seed, mulch, and other materials. It also serves as a record of what was done, to help with future design changes or rotational plantings. Many gardens often look like smaller versions of farms: long, single rows of vegetables with wide alleys between the rows. If you have lots of land and a rototiller, you may choose this system. If you have limited space or would like to maximize space usage, you may choose to use raised beds. See the Raised Beds section for information on how to make a raised bed. Pathways. Whether you choose to plant in rows or beds, make the main pathways in your garden at least 3 feet wide so that you can easily use a wheelbarrow. If you use a garden tractor, make sure you have room to drive in and out of the garden and to turn around if needed. If you plant vegetables in long, single rows, allow enough space to walk between the rows for weeding and harvesting. If your garden is arranged in raised beds, pathways between the beds should be wide enough for you to work. For example, if you work on your knees, measure the distance between the front of your knee and the toe of your shoe, then allow at least this much space for the width of your pathway. Do not make the beds or rows too wide: plan to plant, weed, water and harvest by reaching into the bed while standing or kneeling on the pathway to avoid compacting the soil within the bed. Cover all pathways with mulch or a cover crop to control weeds in the alleys and to keep your feet clean and dry year-round. For mulch, use wood chips, straw, pine needles, or any other product that is readily available in your area. To make the mulch more effective, first lay down heavy cardboard and then cover with mulch. If you use degradable mulch such as woodchips or straw, scrape the decomposed mulch off the pathways and into the rows or beds every 2 to 3 years and add new, fresh mulch to pathways. If you plant a cover crop in the alleyways, mow it several times a year to keep it from getting too tall and setting seed. If you use this technique, make sure your alleys are wide enough for your lawn mower. See the Cover Crop section for information about', 'Container Gardening The Anywhere Garden Concept! All you needs is sunshine, water, fertilizer, the right growing media, good plant choices and the desire to grow…. Container - Type, Size and Capacity Growing Media Choosing a Location Crop Selection for containers Care – Watering, Fertilization, and Growing Tips (Trellises and Supports) Suggested Vegetables for Container Growing'] reference_contexts=None retrieved_context_ids=None reference_context_ids=None response='Based on the provided context, the first step to growing a healthy and productive vegetable garden is selecting a site that has these four important elements:\n\n1. Full sunlight (most summer vegetable crops need at least eight hours of direct sunlight a day).\n2. Easy access to water.\n3. Protection from heavy winds.\n4. Soil with good tilth.\n\nAdditionally, when choosing a location, you should consider decisions regarding best sun access and wind protection, what the site needs in terms of soil enhancement, and your own needs as a gardener so that it is where and what you want it to be.' multi_responses=None reference='\n    Choose a vegetable garden site with full sunlight, easy access to water,\n    protection from heavy winds, and soil with good tilth. Most summer\n    vegetable crops need at least eight hours of direct sunlight per day.\n    ' rubrics=None persona_name=None query_style=None query_length=None

In [28]:
from langchain_core.embeddings import Embeddings

class SentenceTransformerAdapter(Embeddings):
    def __init__(self, embedder):
        self.embedder = embedder

    def embed_documents(self, texts):
        return self.embedder.encode(
            texts,
            normalize_embeddings=True
        ).tolist()

    def embed_query(self, text):
        return self.embedder.encode(
            text,
            normalize_embeddings=True
        ).tolist()


ragas_embeddings = SentenceTransformerAdapter(embedder)

In [32]:
from ragas.metrics import (
    Faithfulness,
    ResponseRelevancy,
    LLMContextPrecisionWithReference,
    LLMContextRecall,
)

faithfulness = Faithfulness(
    llm=evaluator_llm
)

answer_relevance = ResponseRelevancy(
    llm=evaluator_llm,
    embeddings=ragas_embeddings,
    strictness=1
)

context_precision = LLMContextPrecisionWithReference(
    llm=evaluator_llm
)

context_recall = LLMContextRecall(
    llm=evaluator_llm
)

In [33]:
score = await faithfulness.single_turn_ascore(samples[0])

print(f"Faithfulness: {score:.4f}")

Faithfulness: 1.0000

In [34]:
import pandas as pd

scores = []

for i, sample in enumerate(samples, start=1):
    print(f"Evaluating Query {i}...")

    faithfulness_score = await faithfulness.single_turn_ascore(sample)
    relevance_score = await answer_relevance.single_turn_ascore(sample)
    precision_score = await context_precision.single_turn_ascore(sample)
    recall_score = await context_recall.single_turn_ascore(sample)

    scores.append({
        "Query": i,
        "Faithfulness": faithfulness_score,
        "Answer Relevance": relevance_score,
        "Context Precision": precision_score,
        "Context Recall": recall_score
    })

results_df = pd.DataFrame(scores)

results_df

Evaluating Query 1...
Evaluating Query 2...
Evaluating Query 3...
Evaluating Query 4...
Evaluating Query 5...

   Query  Faithfulness  Answer Relevance  Context Precision  Context Recall
0      1           1.0          0.579308           1.000000             1.0
1      2           1.0          0.689938           0.833333             1.0
2      3           1.0          0.670021           1.000000             1.0
3      4           1.0          1.000000           0.500000             1.0
4      5           1.0          1.000000           0.833333             1.0

In [35]:
metric_averages = results_df[
    [
        "Faithfulness",
        "Answer Relevance",
        "Context Precision",
        "Context Recall"
    ]
].mean()

print(metric_averages)

Faithfulness         1.000000
Answer Relevance     0.787853
Context Precision    0.833333
Context Recall       1.000000
dtype: float64

In [36]:
weakest_dimension = metric_averages.idxmin()
weakest_score = metric_averages.min()

print(f"Weakest dimension: {weakest_dimension}")
print(f"Average score: {weakest_score:.4f}")

Weakest dimension: Answer Relevance
Average score: 0.7879

## Part 5: Review a classmate’s pull request
Review a classmate’s Week 5 pull request. Give specific feedback on their RAG pipeline or retrieval evaluation, and include the review URL with your Canvas submission.

Project review: https://github.com/fdx-hw/cosc-650/pull/17#issuecomment-5861215387